services:
  - type: web
    name: youruni
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind=0.0.0.0:$PORT --worker-class=eventlet --log-level=info
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: WEB_CONCURRENCY
        value: 4
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: AES_MASTER_KEY
        generateValue: true
      - key: SECRET_KEY
        generateValue: true
